version: '3'
services:
  spark-master:
    image: register.loc:500/spark:3
    ports:
      - "8082:8080"
    networks:
      - spark-network
    deploy:
      resources:
        limits:
          memory: "1g"
        reservations:
          memory: "1g"
  spark-worker:
    image: register.loc:500/spark:3
    ports:
      - "8083:8081"
    networks:
      - spark-network
    environment:
      SPARK_MASTER: "spark://spark-master:7077"
      SPARK_WORKER_MEMORY: "1g"
      SPARK_WORKER_CORES: 1
    deploy:
      replicas: 1
      resources:
        limits:
          memory: "1g"
        reservations:
          memory: "1g"
  spark-worker2:
    image: register.loc:500/spark:3
    ports:
      - "8084:8081"
    networks:
      - spark-network
    environment:
      SPARK_MASTER: "spark://spark-master:7077"
      SPARK_WORKER_MEMORY: "1g"
      SPARK_WORKER_CORES: 1
    deploy:
      replicas: 1
      resources:
        limits:
          memory: "1g"
        reservations:
          memory: "1g"
  zeppelin:
    image: register.loc:500/zeppelin:4
    ports:
      - "8081:8080"
      - "4040:4040"
    networks:
      - spark-network
    environment:
      SPARK_MASTER: "spark://spark-master:7077"
    deploy:
      resources:
        limits:
          memory: "1g"
        reservations:
          memory: "1g"
networks:
   spark-network:
