version: '3'
services:
  spark-master:
    image: register.loc:500/spark:3
    ports:
      - "8081:8080"
    networks:
      - spark-network
  spark-worker:
    image: register.loc:500/spark:3
    ports:
      - "8180:8180"
    networks:
      - spark-network
    environment:
      SPARK_MASTER: "spark://spark-master:7077"
    deploy:
      replicas: 2
  zeppelin:
    image: register.loc:500/zeppelin:4
    ports:
      - "8082:8080"
    networks:
      - spark-network
    environment:
      SPARK_MASTER: "spark://spark-master:7077"
networks:
   spark-network:
