version: '3'
services:
  spark-master:
    image: register.loc:500/spark:3
    ports:
      - "8081:8080"
    networks:
      - spark-network
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          memory: 800M
  spark-worker:
    image: register.loc:500/spark:3
    ports:
      - "8180:8180"
    networks:
      - spark-network
    environment:
      SPARK_MASTER: "spark://spark-master:7077"
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 1000M
  zeppelin:
    image: register.loc:500/zeppelin:4
    ports:
      - "8082:8080"
    networks:
      - spark-network
    environment:
      SPARK_MASTER: "spark://spark-master:7077"
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 1000M
networks:
   spark-network:
