- name: install git
  yum:
    name: git
    state: present

- name: install wget
  yum:
    name: wget
    state: present

- name: install java
  yum:
    name: java
    state: present

- file:
    path: /opt/jenkins
    state: directory
    owner: root
    mode: 0755

- name: "dowload jenkins"
  get_url:
    url:   "http://mirrors.jenkins.io/war-stable/latest/jenkins.war"
    dest:  "/opt/jenkins/jenkins.war"
    owner: centos

- name: jenkins service
  template: src=jenkins.service dest=/etc/systemd/system/jenkins.service mode=644
  notify:
    - reload systemd

- firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: yes
